export const suggestions = [
  '256 / 8',
  'How big is the Atlantic Ocean?',
  'Distance from Earth to Mars',
  'Population of Canada',
  'Speed of light in km/h',
  'sqrt(144)',
  'sin(pi/2)',
  'What is quantum computing?',
  'GDP of Japan',
  'Who founded Apple?',
  'Atomic weight of gold',
  'How far is the moon?',
  'log(1000)',
  'React framework',
  'History of the internet',
  '2^10',
  'What is machine learning?',
  'Boiling point of water',
  'cos(0)',
  'Capital of Australia',
];
